name: Test deployment

# 如果你想要进一步定义触发条件、路径等，可以查看文档
# https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
defaults:
  run:
    # Docusaurus 项目不在根目录，配置默认工作目录 https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-set-the-default-shell-and-working-directory
    working-directory: docs

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          # https://github.com/actions/setup-node#caching-global-packages-data
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
